SECRET_KEY = '2asTNbQ4gN2K0HAIm6JWx0VM5wiMyzd4'
SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite'
UPLOAD_FOLDER = '/uploads'
MAX_CONTENT_LENGTH = 16 * 1000 * 1000
TEMPLATES_AUTO_RELOAD = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
WEATHER_KEY = ''
